services:
  keycloak:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - 80:8080
      - 8443:8443
    volumes:
      - ./src/main/resources/keycloak/keycloak.pem:/etc/x509/https/tls.crt
      - ./src/main/resources/keycloak/keycloakKey.pem:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    networks:
      - spring-demo
    command:
      - "start-dev"
networks:
  spring-demo:
    driver: bridge

volumes:
  keycloak:
    driver: local
